services:
  - type: web
    name: business-sales-backend
    env: node
    region: oregon
    plan: free
    buildCommand: bun install --production
    startCommand: bun index.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    healthCheckPath: /health
    autoDeploy: true 